# Generated by Django 3.1.6 on 2021-05-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='jumlah_tbs',
            new_name='bulan',
        ),
        migrations.AddField(
            model_name='dataset',
            name='jumlah_tandan',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='rata_berat',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataset',
            name='tahun',
            field=models.IntegerField(default=int),
            preserve_default=False,
        ),
    ]
