# Generated by Django 3.1.6 on 2021-05-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlr', '0003_dataset_curah_hujan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='hasil_produksi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='jumlah_pokok',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='luas_lahan',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='rata_berat',
            field=models.FloatField(),
        ),
    ]
