# Generated by Django 3.1.6 on 2021-05-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlr', '0004_auto_20210523_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='jumlah_pokok',
            field=models.IntegerField(),
        ),
    ]
